-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.16 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2014-03-13 12:14:59
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping database structure for test
CREATE DATABASE IF NOT EXISTS `test` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `test`;


-- Dumping structure for table test.movies
CREATE TABLE IF NOT EXISTS `movies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titel` varchar(255) CHARACTER SET latin1 COLLATE latin1_german1_ci NOT NULL,
  `original_title` varchar(255) DEFAULT NULL,
  `produktionsland` varchar(50) NOT NULL,
  `duration` int(11) NOT NULL,
  `release_year` year(4) DEFAULT NULL,
  `genre` varchar(128) NOT NULL,
  `director` varchar(100) NOT NULL,
  `screenwriter` varchar(100) NOT NULL,
  `music` varchar(100) DEFAULT NULL,
  `oscars` varchar(10) NOT NULL,
  `fsk` varchar(50) DEFAULT NULL,
  `actors` text NOT NULL,
  `movie_poster` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=212 DEFAULT CHARSET=latin1;

-- Dumping data for table test.movies: ~23 rows (approximately)
/*!40000 ALTER TABLE `movies` DISABLE KEYS */;
INSERT INTO `movies` (`id`, `titel`, `original_title`, `produktionsland`, `duration`, `release_year`, `genre`, `director`, `screenwriter`, `music`, `oscars`, `fsk`, `actors`, `movie_poster`) VALUES
	(100, 'Star Wars: Episode I – Die dunkle Bedrohung', 'Star Wars: Episode I – The Phantom Menace', 'USA', 128, '1999', 'Science-Fiction', 'George Lucas', 'George Lucas', 'John Williams', '0', 'ab 6 Jahre', 'Liam Neeson: Qui-Gon Jinn\r\nEwan McGregor: Obi-Wan Kenobi\r\nNatalie Portman: Königin Amidala (Padmé Naberrie)\r\nJake Lloyd: Anakin Skywalker\r\nPernilla August: Shmi Skywalker\r\nFrank Oz: Yoda\r\nIan McDiarmid: Senator Palpatine (Darth Sidious)\r\nRay Park/Peter Serafinowicz (Stimme): Darth Maul\r\nHugh Quarshie: Captain Panaka\r\nAhmed Best: Jar Jar Binks\r\nAnthony Daniels: C-3PO\r\nKenny Baker: R2-D2\r\nTerence Stamp: Kanzler Valorum\r\nBrian Blessed: Boss Nass\r\nAndrew Secombe: Watto\r\nLewis Macleod: Sebulba\r\nSilas Carson: Vizekönig Nute Gunray, Ki-Adi-Mundi, Lott Dodd\r\nSamuel L. Jackson: Mace Windu\r\nKeira Knightley: Sabé\r\n', 'Star_Wars_Episode1-Poster.jpg'),
	(125, 'Star Wars: Episode II – Angriff der Klonkrieger', 'Star Wars: Episode II – Attack of the Clones', 'USA', 137, '2002', 'Science-Fiction', 'George Lucas', 'George Lucas', 'John Williams', '0', 'ab 12 Jahre', 'Hayden Christensen: Anakin Skywalker\r\nEwan McGregor: Obi-Wan Kenobi\r\nNatalie Portman: Senatorin Padmé Amidala\r\nChristopher Lee: Count Dooku/Darth Tyranus\r\nSamuel L. Jackson: Mace Windu\r\nFrank Oz: Yoda\r\nIan McDiarmid: Kanzler Palpatine/Darth Sidious\r\nPernilla August: Shmi Skywalker-Lars\r\nTemuera Morrison: Jango Fett, Klonsoldaten\r\nDaniel Logan: Boba Fett\r\nJimmy Smits: Senator Bail Organa\r\nLeeanna Walsman: Zam Wesell\r\nAhmed Best: Jar Jar Binks\r\nAndy Secombe: Watto\r\nAnthony Daniels: C-3PO\r\nSilas Carson: Ki-Adi-Mundi, Vizekönig Nute Gunray\r\n', 'star_wars_episode_two.jpg'),
	(138, 'Der Herr der Ringe: Die Gefährten', 'The Lord of the Rings: The Fellowship of the Ring', 'USA, Neuseeland', 178, '2001', 'Fantasy', 'Peter Jackson', 'Fran Walsh, Philippa Boyens, Peter Jackson', 'Howard Shore', '4', 'ab 12 Jahre', 'Elijah Wood: Frodo Beutlin\r\nIan McKellen: Gandalf\r\nSean Astin: Samweis Gamdschie\r\nViggo Mortensen: Aragorn/Streicher\r\nLiv Tyler: Arwen Undomiel\r\nSean Bean: Boromir\r\nOrlando Bloom: Legolas\r\nJohn Rhys-Davies: Gimli\r\nChristopher Lee: Saruman\r\nDominic Monaghan: Meriadoc Brandybock\r\nBilly Boyd: Peregrin Tuk\r\nCate Blanchett: Galadriel\r\nHugo Weaving: Elrond\r\nIan Holm: Bilbo Beutlin', 'herr-ringe-gefaehrten.jpg'),
	(139, 'Der Herr der Ringe: Die Zwei Türme', 'The Lord of the Rings: The Two Towers', 'USA, Neuseeland', 179, '2002', 'Fantasy', 'Peter Jackson', 'Fran Walsh, Philippa Boyens, Peter Jackson', 'Howard Shore', '2', 'ab 12 Jahre', 'Elijah Wood: Frodo Beutlin\r\nSean Astin: Samweis Gamdschie\r\nViggo Mortensen: Aragorn\r\nIan McKellen: Gandalf\r\nDominic Monaghan: Meriadoc Brandybock\r\nBilly Boyd: Peregrin Tuk\r\nOrlando Bloom: Legolas\r\nJohn Rhys-Davies: Gimli/Baumbart (Stimme)\r\nAndy Serkis: Gollum/Sméagol\r\nChristopher Lee: Saruman\r\nBernard Hill: Théoden\r\nMiranda Otto: Éowyn\r\nKarl Urban: Éomer\r\nBrad Dourif: Gríma Schlangenzunge\r\nLiv Tyler: Arwen Undomiel\r\nHugo Weaving: Elrond\r\nDavid Wenham: Faramir\r\nCate Blanchett: Galadriel', 'DerHerrderRingeDiezweiTurme.jpg'),
	(140, 'Der Herr der Ringe: Die Rückkehr des Königs', 'The Lord of the Rings: The Return of the King', 'USA, Neuseeland', 201, '2003', 'Fantasy', 'Peter Jackson', 'Fran Walsh, Philippa Boyens, Peter Jackson', 'Howard Shore', '11', 'ab 12 Jahre', 'Viggo Mortensen: Aragorn / Elessar\r\nLiv Tyler: Arwen Undómiel\r\nIan McKellen: Gandalf\r\nChristopher Lee: Saruman[4]\r\nSean Bean: Boromir\r\nIan Holm: Bilbo Beutlin\r\nMarton Csokas: Celeborn\r\nJohn Noble: Denethor\r\nHugo Weaving: Elrond\r\nKarl Urban: Éomer\r\nMiranda Otto: Éowyn\r\nDavid Wenham: Faramir\r\nElijah Wood: Frodo Beutlin\r\nCate Blanchett: Galadriel\r\nJohn Rhys-Davies: Gimli / Baumbart (Stimme)\r\nBrad Dourif: Grima Schlangenzunge\r\nAndy Serkis: Gollum / Sméagol\r\nLawrence Makoare: Gothmog / Hexenkönig\r\nPaul Norell: König der Toten\r\nOrlando Bloom: Legolas\r\nDominic Monaghan: Meriadoc Brandybock\r\nBilly Boyd: Peregrin Tuk\r\nSean Astin: Samweis Gamdschie\r\nAlan Howard: Stimme Saurons\r\nIan Hughes: Irolas\r\nBernard Hill: Théoden', 'Der_Herr_der_Ringe_-_Die_R_ckkehr_des_K_nigs.jpg'),
	(145, 'Simpsons- Der Film', 'The Simpsons Movie', 'USA', 83, '2007', 'Zeichentrick', 'David Silverman, Produzent: Matt Groening', 'James L. Brooks, Matt Groening u.a.', 'Hans Zimmer', '0', 'ab 6 Jahre', 'Synchronstimmen:\r\nHomer Simpson: Norbert Gastell (Dan Castellaneta)\r\nMarge Simpson: Anke Engelke (Julie Kavner)\r\nBart Simpson: Sandra Schwittau (Nancy Cartwright)\r\nLisa Simpson: Sabine Bohlmann (Yeardley Smith)\r\nKrusty, der Clown: 	Hans-Rainer Müller (Dan Castellaneta)\r\nRektor Seymour Skinner: Klaus Guth (Harry Shearer)\r\nRalph Wiggum: Beate Pfeiffer (Nancy Cartwright)\r\nNed Flanders: Ulrich Frank (Harry Shearer)', 'simpsons_movie.jpg'),
	(146, 'Paranormal Activity 2', 'Paranormal Activity 2', 'USA', 91, '2010', 'Horror', 'Tod Williams', 'Michael R. Perry, Christopher B. Landon', 'Michael Simmonds', '0', 'ab 16 Jahre', 'Micah Sloat: Micah\r\nKatie Featherston: Katie\r\nBrian Boland: Daniel „Dan“ Rey\r\nSprague Grayden: Kristi Rey\r\nMolly Ephraim: Ali\r\nTim Clemens: Hunter\r\n', 'paranormal2_poster_lg.jpg'),
	(147, 'Der Fluch der Karibik - Teil 1', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'USA', 137, '2003', 'Action', 'Gore Verbinski', 'Ted Elliott, Terry Rossio', 'Klaus Badelt', '1', 'ab 12 Jahre', 'Johnny Depp: Captain Jack Sparrow\r\nOrlando Bloom: William „Will“ Turner\r\nGeoffrey Rush: Captain Hector Barbossa\r\nKeira Knightley: Elizabeth Swann\r\nJack Davenport: Commodore James Norrington\r\nJonathan Pryce: Gouverneur Weatherby Swann\r\nKevin R. McNally: Joshamee Gibbs\r\nLee Arenberg: Pintel\r\nMackenzie Crook: Ragetti\r\nDamian O’Hare: Lt. Gillette\r\nMartin Klebba: Marty\r\nDavid Bailie: Cotton\r\nZoë Saldaña: Anamaria\r\nLauren Maher: Scarlett\r\nVanessa Branch: Giselle', 'FluchderKaribik-Poster02.jpg'),
	(148, 'Banana Joe', 'Banana Joe', 'Italien', 96, '1981', 'Action', 'Steno (Stefano Vanzina)', 'Bruno Corbucci, Bud Spencer', 'Oliver Onions', '0', 'ab 6 Jahre', 'Bud Spencer: Banana Joe\r\nMarina Langner: Dorianne\r\nMario Scarpetta: Manuel\r\nGianfranco Barra: Torcillo\r\nEnzo Garinei: Moreno\r\nGunther Philipp: Sarto\r\nGiorgio Bracardi: Martino', 'banana_joe_spencer.jpg'),
	(151, 'Zwei Himmelhunde auf dem Weg zur Hölle', 'Più forte, ragazzi!', 'Italien', 102, '1972', 'Action', 'Giuseppe Colizzi', 'Barbara Alberti, Giuseppe Colizzi', 'Guido & Maurizio De Angelis ', '0', 'ab 16 Jahre', 'Terence Hill: Plata\r\nBud Spencer: Salud\r\nReinhard Kolldehoff: Mr. Ears\r\nRiccardo Pizzuti: Naso\r\nCyril Cusack: Matto\r\nAlexander Allerson: Saluds Bruder\r\n', 'zwei_himmelhunde_auf_dem_weg_zur_hoelle.jpg'),
	(152, 'Matrix', 'The Matrix', 'USA', 131, '1999', 'Science-Fiction', 'Wachowski-Geschwister', 'Wachowski-Geschwister', 'Don Davis', '4', 'ab 16 Jahre', 'Keanu Reeves: Neo/Thomas A. Anderson\r\nLaurence Fishburne: Morpheus\r\nCarrie-Anne Moss: Trinity\r\nHugo Weaving: Agent Smith\r\nGloria Foster: Das Orakel\r\nPaul Goddard: Agent Brown\r\nRobert Taylor: Agent Jones\r\nJoe Pantoliano: Cypher\r\n', 'matrix_ver1_.jpg'),
	(155, 'Lara Croft: Tomb Raider', 'Lara Croft: Tomb Raider', 'USA, UK, Japan', 100, '2001', 'Action', 'Simon West', 'Patrick Massett, John Zinman', 'Graeme Revell', '0', 'ab 12 Jahre', 'Angelina Jolie: Lara Croft\r\nJon Voight: Lord Richard Croft\r\nIain Glen: Manfred Powell\r\nNoah Taylor: Bryce\r\nDaniel Craig: Alex West\r\nLeslie Phillips: Wilson\r\nChristopher Barrie: Hillary', 'lara_croft_tomb_raider_xlg.jpg'),
	(175, 'James Bond 007: Skyfall', 'James Bond 007: Skyfall', 'UK', 143, '2012', 'Action', 'Sam Mendes', 'Barbara Broccoli, Michael G. Wilson', 'Thomas Newman, Titellied: Adele', '2', 'ab 12 Jahre', 'Daniel Craig: James Bond („007“)\r\nJudi Dench: „M“\r\nJavier Bardem: Raoul Silva\r\nRalph Fiennes: Gareth Mallory\r\nNaomie Harris: Eve Moneypenny\r\nBérénice Marlohe: Sévérine\r\nAlbert Finney: Kincade\r\nBen Whishaw: „Q“\r\nRory Kinnear: Bill Tanner', 'Skyfall-Classic-Poster.jpg'),
	(176, 'James Bond 007: Stirb an einem anderen Tag', 'James Bond 007: Die Another Day', 'USA, UK', 133, '2002', 'Action', 'Lee Tamahori', 'Barbara Broccoli, Michael G. Wilson', 'David Arnold, Titelsong: Madonna', '0', 'ab 12 Jahre', 'Pierce Brosnan: James Bond\r\nHalle Berry: Jacintha „Jinx“ Johnson\r\nToby Stephens: Colonel Tan-Sun Moon / Gustav Graves\r\nRosamund Pike: Miranda Frost\r\nRick Yune: Zao\r\nWill Yun Lee: Colonel Tan-Sun Moon\r\nKenneth Tsang: General Moon\r\nJudi Dench: M\r\nJohn Cleese: Q\r\nSamantha Bond: Miss Moneypenny\r\nColin Salmon: Charles Robinson\r\nMichael Madsen: Damian Falco\r\nEmilio Echevarría: Raoul\r\nLawrence Makoare: Mr. Kil\r\nHo Yi: Mr. Chang\r\nMadonna: Verity (Cameo-Auftritt)', 'poster_james-bond-007-dieAnotherDay.jpg'),
	(188, '17 Mädchen', '17 filles', 'Frankreich', 87, '2011', 'Drama', 'Delphine Coulin, Mouriel Coulin', 'Delphine Coulin, Mouriel Coulin', NULL, '0', 'ab 12 Jahre', 'Louise Grinberg: Camille\r\nJuliette Darche: Julia\r\nRoxane Duran: Florence\r\nEsther Garrel: Flavie\r\nSolène Rigot: Mathilde\r\nYara Pilartz: Clémentine\r\nFlorence Thomassin: Camilles Mutter\r\nCarlo Brandt: Schulleiter\r\nFrédéric Noaille: Florian', '17-maedchen_poster.jpg'),
	(192, 'Kokowääh', 'Kokowääh', 'Deutschland', 123, '2011', 'Komödie', 'Til Schweiger', 'Til Schweiger', 'Dirk Reichardt, Mirko Schaffer', '0', 'ab 6 Jahre', 'Til Schweiger: Henry\r\nEmma Schweiger: Magdalena\r\nJasmin Gerat: Katharina\r\nSamuel Finzi: Tristan\r\nMeret Becker: Charlotte\r\nAnna Julia Kapfelsperger: Henrys Liaison Bine\r\nFriederike Kempter: Henrys Agentin\r\nMiranda Leonhardt: Katharinas Haushälterin Maria\r\nMišel Mati?evi?: Filmregisseur Rob Kaufmann\r\nSönke Möhring: Polizist\r\nJessica Richter: Henrys Liaison Esther\r\nKatharina Thalbach: Patientin mit Maulsperre\r\nJohann von Bülow: Feuerwehrmann\r\nUlrich Wickert: Moderator\r\nAnne-Sophie Briest: Mutter im Supermarkt\r\nLuna Schweiger: Tochter im Supermarkt\r\nBirthe Wolter: Arzthelferin\r\nFahri Ogün Yard?m: Pizzabote', 'Kokowaah-Poster01.jpg'),
	(196, 'Vaterfreuden', 'Vaterfreuden', 'Deutschland', 106, '2014', 'Komödie', 'Matthias Schweighöfer', 'Sebastian Wehlings', 'Martin Todsharow', '0', 'ab 6 Jahre', 'Matthias Schweighöfer: Felix\r\nIsabell Polak: Maren\r\nTom Beck: Ralph\r\nFriedrich Mücke: Henne\r\nNatalia Belitski: Jessie\r\nLina Hüesker: Leonie\r\nMoritz Grove: Tom\r\nAlexander Khuon: Norbert\r\nLuise Bähr: Sybille\r\nKatharina Schüttler: Betti\r\nTim Sander: Frederic Sattelmeyer\r\nDetlev Buck: Dr. Parisius\r\nSusan Hoecke: Kara\r\nMargarita Broich: Dr. Metzler\r\nMichael Gwisdek: Vater von Felix\r\nEmilia Schüle: Lisa\r\nGitta Schweighöfer: Hebamme', 'Vaterfreuden-DE-Poster.jpg'),
	(200, 'Stromberg - Der Film', 'Stromberg - Der Film', 'Deutschland', 123, '2014', 'Komödie', 'Arne Feldhusen', 'Ralf Husmann', '', '0', 'ab 12 Jahre', 'Christoph Maria Herbst: Bernd Stromberg\r\nBjarne Mädel: Berthold „Ernie“ Heisterkamp\r\nOliver Wnuk: Ulf Steinke\r\nDiana Staehly: Tanja Steinke (geb. Seifert)\r\nMilena Dreißig: Jennifer Schirrmann\r\nLaurens Walter: Lars Lehnhoff\r\nMaja Beckmann: Sabine „Sabbel“ Buhrer\r\nPeter Rütten: Herr Pötsch\r\nCarsten Meyer (Musiker): Alleinunterhalter Günni\r\nMichael Wittenborn: Capitol-Vorstand Klaus Klinkhammer\r\nJürgen Rißmann: Hausmeister', 'Stromberg_film_Plakat.jpg'),
	(201, 'Scary Movie', 'Scary Movie', 'USA', 88, '2000', 'Komödie', 'Keenen Ivory Wayans', 'Shawn Wayans, Marlon Wayans', 'David Kitay', '0', 'ab 16 Jahre', 'Anna Faris: Cindy Campbell\r\nJon Abrahams: Bobby Prinze\r\nShannon Elizabeth: Buffy Gilmore\r\nLochlyn Munro: Greg Phillipe\r\nShawn Wayans: Ray Wilkins\r\nMarlon Wayans: Shorty Meeks\r\nRegina Hall: Brenda Meeks\r\nDave Sheridan: Doofy Gilmore\r\nCarmen Electra: Drew Decker\r\nCheri Oteri: Gail Hailstorm', 'scary_movie.jpg'),
	(202, 'Rocky Balboa', 'Rocky Balboa', 'USA', 98, '2006', 'Drama', 'Sylvester Stallone', 'Sylvester Stallone', 'Bill Conti', '0', 'ab 12 Jahre', 'Sylvester Stallone: Robert „Rocky“ Balboa, sr.\r\nBurt Young: Paulie Pennino\r\nMilo Ventimiglia: Robert Balboa, jr.\r\nGeraldine Hughes: Marie\r\nTony Burton: Tony „Duke“ Everson\r\nAntonio Tarver: Mason „The Line“ Dixon\r\nJames Francis Kelly: Steps\r\nTalia Shire: Adrian Balboa\r\nLou DiBella: Lou DiBella\r\nMike Tyson: Mike Tyson', 'rockybalboa.jpg'),
	(205, 'Rocky I', 'Rocky I', 'USA', 114, '1976', 'Action', 'John G. Avildsen', 'Sylvester Stallone', 'Bill Conti', '3', 'ab 12 Jahre', 'Sylvester Stallone: Robert „Rocky“ Balboa\r\nTalia Shire: Adrianna „Adrian“ Pennino\r\nBurt Young: Paulie Pennino\r\nCarl Weathers: Apollo Creed\r\nBurgess Meredith: Michael „Mickey“ Goldmill\r\nTony Burton: Tony „Duke“ Evers\r\nJoe Spinell: Tony Gazzo\r\n', 'rocky_film1.jpg'),
	(210, 'Voll normaaal', 'Voll normaaal', 'Deutschland', 91, '1994', 'Komödie', 'Ralf Huettner', 'Tom Gerhardt', 'Jörg Evers', '0', 'ab 12 Jahre', 'Tom Gerhardt: Tommie Krause/Dieter Krause/Heinz\r\nHilmi Sözer: Mario\r\nGruschenka Stevens: Gabi\r\nEddy Steinblock: Zuhälter Jupp\r\nVeronica Ferres: Carmen Krause\r\nRenate Dissel: Elisabeth (Lisbeth) Krause\r\nUwe Fellensiek: Norbert (Nobbi)\r\nDolly Buster: Gianna S.\r\nKatja Flint: Porschebesitzerin\r\nRolf Zacher: Hütchenspieler\r\nAndreas Kunze: Getränkehändler\r\nAnthony Arndt: Hausmeister\r\n', 'voll_normaaal.jpg'),
	(211, 'Resturlaub', 'Resturlaub', 'Deutschland', 98, '2011', 'Komödie', 'Gregor Schnitzler', 'Tommy Jaud', 'Marco Meister', '0', 'ab 12 Jahre', 'Maximilian Brückner: Peter „Pitschi“ Greulich\r\nMira Bartuschek: Sabine\r\nAntoine Monot, Jr.: Checko\r\nStephan Luca: Arne\r\nJeff Burrell: Jason\r\nMartina Hill: Biggy-Ente\r\nIvanka Brekalo: Miriam\r\nDave Davis: Pfarrer Bouba\r\nMelanie Winiger: Luna\r\nManuela Wisbeck: Heidi\r\nRosetta Pedone: Luisa\r\nPeter Rappenglück: Pfarrer Braun\r\nLeonardo Nigro: Pedro\r\nMatthias Matschke: Stefano\r\nLina Beckmann: Steffi\r\nFred Stillkrauth: Seppelpeter\r\n', 'resturlaub_film.jpg'),
	(222, 'Kill Bill Volume 1', 'Kill Bill: Vol. 1', 'USA', 106, '2003', 'Action', 'Quentin Tarantino', 'Quentin Tarantino', 'The RZA', 'ab 18 Jahre', 'Uma Thurman: Die Braut\r\nDavid Carradine: Bill\r\nLucy Liu: O-Ren Ishii\r\nDaryl Hannah: Elle Driver\r\nVivica A. Fox: Vernita Green\r\nMichael Madsen: Budd\r\nSonny Chiba: Hattori Hanzo\r\nChiaki Kuriyama: Gogo Yubari\r\nJulie Dreyfus: Sofie Fatale\r\nLiu Chia Hui: Johnny Mo\r\n', 'kill_bill_01.jpg'),
    (223, 'Men in Black I', 'Men in Black I', 'USA', 94, '1997', 'Science-Fiction', 'Barry Sonnenfeld', 'Ed Solomon', 'Danny Elfman', 'av 12 Jahre', 'Tommy Lee Jones: Agent K (Kay)\r\nWill Smith: Agent J (Jay)\r\nLinda Fiorentino: Dr. Laurel Weaver\r\nVincent D’Onofrio: Edgar (die Schabe)\r\nRip Torn: Agent Z (Zed)\r\nTony Shalhoub: Jack Jeebs\r\nSiobhan Fallon: Beatrice\r\nMike Nussbaum: Gentle Rosenberg\r\nJon Gries: Nick\r\nSergio Calderón: José\r\nCarel Struycken: Arquillianer\r\nRichard Hamilton: Agent D (Dee)', 'men-in-black-poster1.jpg');
;
/*!40000 ALTER TABLE `movies` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
